apiVersion: v1
kind: Deployment
metadata:
  name: helloapp
  labels:
     app: helloapp
spec:
  replicas:3
  strategy:
    typr: RollingUpdate
  template:
    metadata:
      labels:
         app: helloapp
    spec:
      containers:
      - name: helloapp
      	image: jnaru/hello-k8s
      	port: 
	- containerPort:8084
